// Shared style tokens across all admin tabs — keeps visual consistency
// without needing a CSS framework. Matches the candidate-facing pages'
// existing palette (same grays, same blue accent) for continuity.

export const sharedStyles: Record<string, React.CSSProperties> = {
  sectionTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#111827',
    margin: '0 0 4px 0',
  },
  sectionDesc: {
    fontSize: 13,
    color: '#6B7280',
    margin: '0 0 20px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 13,
  },
  th: {
    textAlign: 'left',
    padding: '10px 12px',
    color: '#6B7280',
    fontWeight: 600,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '0.03em',
    borderBottom: '1px solid #E5E7EB',
  },
  td: {
    padding: '12px',
    borderBottom: '1px solid #F3F4F6',
    color: '#374151',
  },
  primaryBtn: {
    padding: '9px 16px',
    borderRadius: 6,
    border: 'none',
    backgroundColor: '#1D4ED8',
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  secondaryBtn: {
    padding: '9px 16px',
    borderRadius: 6,
    border: '1px solid #D1D5DB',
    backgroundColor: '#FFFFFF',
    color: '#374151',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
  },
  dangerBtn: {
    padding: '7px 12px',
    borderRadius: 6,
    border: '1px solid #FCA5A5',
    backgroundColor: '#FFFFFF',
    color: '#DC2626',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
  },
  input: {
    padding: '9px 12px',
    borderRadius: 6,
    border: '1px solid #D1D5DB',
    fontSize: 13,
    outline: 'none',
  },
  label: {
    fontSize: 12,
    fontWeight: 500,
    color: '#374151',
    marginBottom: 4,
    display: 'block',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 14,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    border: '1px solid #E5E7EB',
    padding: '24px',
  },
  badge: {
    fontSize: 11,
    fontWeight: 600,
    padding: '3px 8px',
    borderRadius: 5,
  },
  emptyState: {
    textAlign: 'center',
    padding: '40px 0',
    color: '#9CA3AF',
    fontSize: 13,
  },
  modal: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: '28px',
    maxWidth: 520,
    width: '90%',
    maxHeight: '85vh',
    overflowY: 'auto',
  },
};